### @name SUCCESSFUL_LOGIN
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password": "password"
}

### @name FAILURE_LOGIN
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password": "passwords"
}

### @name EMPTY_BODY_LOGIN
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{}

### @name SUCCESSFUL_REGISTER
POST http://127.0.0.1:8000/api/register
Content-Type: application/json

{
    "email" : "newman@gmail.com",
    "password": "password",
    "name": "New Man",
    "password_confirmation": "password"
}

### @name FAILURE_REGISTRATION
POST http://127.0.0.1:8000/api/register
Content-Type: application/json

{
    "email" : "newman@gmail",
    "password": "password",
    "password_confirmation": "passwordS"
}

### @name SUCCESSFUL_LOGGED_IN_USER
GET http://127.0.0.1:8000/api/user
Content-Type: application/json
Authorization: Bearer 4|YE5e8CYb1rqdR5xjyRUNzHHXz2Akp0FOwmr0s9gd

### @name WRONG_BEARER_TOKEN
GET http://127.0.0.1:8000/api/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer 4|YE5e8CYb1rqdR5xjyRUNzHHXz2Akp0FOwmr0s9gdD

### @name GET_BOOKS
GET http://127.0.0.1:8000/api/books?page=1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|JtEKoKj54DLvDQINtdIiZZcFijCsmjVxGxNL920k

### @name SUCCESSFULLY_ADD_BOOK
POST http://127.0.0.1:8000/api/book/save
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{
    "isbn" : "1911129209078",
    "title": "The hunter, the child and the Fox",
    "publisher": "Global Publishers",
    "number_of_pages": 98
}

### @name FAILURE_ADDING_BOOK
POST http://127.0.0.1:8000/api/book/save
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{
    "isbn" : "1911129209078",
    "title": "The hunter, the child and the Fox",
    "publisher": "Global Publishers"
}

### @name GET_EXISTING_BOOK
GET http://127.0.0.1:8000/api/book/5001/view
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{}

### @name GET_NON_EXISTING_BOOK
GET http://127.0.0.1:8000/api/book/50001/view
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{}

### @name SUCCESSFULL_UPDATE_BOOK
POST http://127.0.0.1:8000/api/book/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{
    "id": 5001,
    "isbn" : "1911129209078-1",
    "title": "The hunter, the child, the Frog and the Fox",
    "publisher": "Global Publishers",
    "number_of_pages": 100
}

### @name FAILURE_UPDATE_BOOK
POST http://127.0.0.1:8000/api/book/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{
    "id": 50015,
    "isbn" : "1911129209078-1",
    "title": "The hunter, the child, the Frog and the Fox",
    "publisher": "Global Publishers",
    "number_of_pages": 100
}

### @name DELETE_BOOK
POST http://127.0.0.1:8000/api/book/remove
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{
    "id": 5001
}

### @name FAILURE_1_DELETE_BOOK
POST http://127.0.0.1:8000/api/book/remove
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{}

### @name FAILURE_2_DELETE_BOOK
POST http://127.0.0.1:8000/api/book/remove
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{
    "id": 45205
}

### @name ALL_USERS
GET http://127.0.0.1:8000/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{}

### @name GET_USER
GET http://127.0.0.1:8000/api/user/2/view
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{}

### @name GET_USER_FAVORITE_BOOKS
GET http://127.0.0.1:8000/api/user/2/books/favourites
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{}

### @name GET_USER_LIKED_BOOKS
GET http://127.0.0.1:8000/api/user/2/books/likes
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{}

### @name GET_USER_COMMENTED_BOOKS
GET http://127.0.0.1:8000/api/user/2/books/comments
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{}

### @name UPDATE_USER
POST http://127.0.0.1:8000/api/user/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{
    "id" : 2,
    "name": "Normal User 1",
    "email": "normaluser@gmail.com"
}

### @name FAILED_UPDATE_USER
POST http://127.0.0.1:8000/api/user/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{
    "id" : 10,
    "name": "Normal User 1",
    "email": "normaluser@gmail.com"
}

### @name REMOVE_USER
POST http://127.0.0.1:8000/api/user/remove
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{
    "id" : 10
}

### @name REMOVE_USER
POST http://127.0.0.1:8000/api/user/remove
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{
    "id" : 2
}

### @name FAILED_1_REMOVE_USER
POST http://127.0.0.1:8000/api/user/remove
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{
    "id" : 20
}

### @name FAILED_2_REMOVE_USER
POST http://127.0.0.1:8000/api/user/remove
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{}

### @name FAILED_3_REMOVE_USER
POST http://127.0.0.1:8000/api/user/remove
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|cwrTDC2cnkYTqDjaCGKAzShkRBwya56WyYzqzvNw

{
    "id" : 1
}



